// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientMessage =
  | { type: "request_grid_state" }
  | { type: "tile_update"; col: number; row: number; data: HexTile }
  | { type: "None" };

export type HexTile =
  | "Wild"
  | { Mine: MineData }
  | { Turret: TurretData }
  | "Slime";

export type MineData = {
  level: number;
  count: number;
  capacity: number;
  state: string;
  trade_value: number;
};

export type ServerMessage =
  | {
      type: "grid_state";
      width: number;
      height: number;
      tiles: Array<TileState>;
    }
  | { type: "tile_update"; col: number; row: number; data: HexTile };

export type TileState = { col: number; row: number; data: HexTile };

export type TurretData = { level: number; state: string };
